### PR TITLE
#5 Add support for secrity token extension.

### PR DESCRIPTION
**Pull request by petkivim**
#5 Add support for securityToken SOAP header. Update common, client and
server components. Add test cases for testing the following scenarious:

- securityToken element and tokenType attribute are both present, and
they have the same namespace prefix
- securityToken element and tokenType attribute are both present,
tokenType lacks namespace prefix
- securityToken element is present, tokenType attribute is missing

If tokenType is empty or not defined, the attributed is omitted on SOAP
message generation.

Add a new request-response example pair without wrappers and with
securityToken SOAP header.

############

#7 Earlier ```Server``` component has generated the response header creating a new SOAP message with an empty header, then adding required header elements and copying all the values from the request message header. Header values have remained the same, but the order of the elements might have changed. The ```Server``` component has hard coded order for header elements when a new response message is generated. According to [X-Road message protocol](https://github.com/vrk-kpa/X-Road/blob/develop/doc/Protocols/pr-mess_x-road_message_protocol.md) the service MUST copy all the header fields from the request to the response in the exact same sequence with the exact same values.

Now the ```Server``` component clones the request message, removes all the elements from the body and uses the cloned request message as a template for the response message. In this way the order and the values of the SOAP header are kept.

### CODE REVIEW

**Comment by hanhaka** [comment]
Thanks for contributing to xrd4j development!

Development team will look at the content of PR more closely in near future. Before that, the work estimate to complete the review of PR is estimated and the actual review work starts after that.

Regards,
Hannu

**Comment by iluwatar** [comment]
Hi @petkivim :wave: The pull request has some conflicts that need to be resolved. Can you update it and I will review?

**Comment by petkivim** [comment]
Hi @iluwatar I have updated the pull request and all the conflicts should be fixed now.

**Review by iluwatar — CHANGES_REQUESTED** [review]
The changes look good. Only two minor issues prevent merging:
- The build is currently failing due to couple of Checkstyle issues
- `src/CHANGELOG.md` should be amended with change description

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Thanks for the improvements :+1:

**Pull request merged**
